# Generated by Django 3.0.4 on 2020-04-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=9, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=80)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_referencia', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_apertura', models.DateField()),
                ('fecha_resolucion', models.DateField()),
                ('nivel_urgencia', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=1000)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deusto11_nexus_components.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.IntegerField(blank=True, null=True)),
                ('modelo', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('tipo_equipo', models.CharField(max_length=100)),
                ('fecha_adquisicion', models.DateField()),
                ('fecha_puesta_en_marcha', models.DateField()),
                ('proveedor_nombre', models.CharField(max_length=50)),
                ('proveedor_telefono', models.IntegerField()),
                ('planta', models.IntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deusto11_nexus_components.Tickets')),
            ],
        ),
    ]
