# Generated by Django 3.0.5 on 2020-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deusto11_nexus_components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=9, null=True)),
                ('name', models.CharField(max_length=7)),
                ('surname', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=20)),
                ('telefone_number', models.IntegerField()),
                ('user_nick', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('machine_type', models.CharField(max_length=100)),
                ('get_date', models.DateField()),
                ('start_up_date', models.DateField()),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_telefone', models.IntegerField()),
                ('floor_on_premise', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('starting_date', models.DateField()),
                ('resolution_date', models.DateField()),
                ('urgency_level', models.CharField(max_length=50)),
                ('ticket_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=1000)),
                ('machine', models.ManyToManyField(to='deusto11_nexus_components.Machine')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.AddField(
            model_name='employee',
            name='ticket',
            field=models.ManyToManyField(to='deusto11_nexus_components.Ticket'),
        ),
    ]
