# Generated by Django 3.0.5 on 2020-04-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deusto11_nexus_components', '0002_auto_20200422_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dni',
            field=models.CharField(default='12345678R', max_length=9),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_nick',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='set_number',
            field=models.IntegerField(default=7850),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reference_number',
            field=models.IntegerField(default=101),
        ),
    ]
