# Generated by Django 3.0.5 on 2020-05-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deusto11_nexus_components', '0003_auto_20200422_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user', models.IntegerField()),
                ('receive_user', models.IntegerField()),
                ('subjct', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerLoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nick', models.CharField(default='user', max_length=10)),
                ('password', models.CharField(default='password', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='dni',
            field=models.CharField(default='12345678R', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_nick',
            field=models.CharField(default='user', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='set_number',
            field=models.IntegerField(default=7850, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reference_number',
            field=models.IntegerField(default=101, unique=True),
        ),
    ]
