# Generated by Django 3.0.5 on 2020-05-22 18:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('deusto11_nexus_components', '0004_auto_20200521_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='telefone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='provider_telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
