# Generated by Django 3.0.5 on 2020-05-22 23:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('deusto11_nexus_components', '0005_auto_20200522_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dni',
            field=models.CharField(default='XXXXXXXXR', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(default='nombre@dominio.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telefone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+00000000000', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='provider_telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+00000000000', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reference_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
