# Generated by Django 3.0.5 on 2020-05-23 19:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('deusto11_nexus_components', '0007_auto_20200523_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='receive_user',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='email',
            name='send_user',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telefone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+4152XXXXXXX', max_length=128, region=None, unique=True),
        ),
    ]
